CREATE TABLE IF NOT EXISTS patients(id SERIAL PRIMARY KEY, name TEXT NOT NULL, age INT, gender TEXT, phone TEXT, address TEXT, admitted_on DATE DEFAULT CURRENT_DATE);
CREATE TABLE IF NOT EXISTS doctors(id SERIAL PRIMARY KEY, name TEXT NOT NULL, specialization TEXT, phone TEXT, fee NUMERIC(10,2) DEFAULT 0);
CREATE TABLE IF NOT EXISTS appointments(id SERIAL PRIMARY KEY, patient_id INT REFERENCES patients(id) ON DELETE CASCADE, doctor_id INT REFERENCES doctors(id) ON DELETE CASCADE, appt_date DATE, status TEXT DEFAULT 'Scheduled');
CREATE TABLE IF NOT EXISTS treatments(id SERIAL PRIMARY KEY, patient_id INT REFERENCES patients(id) ON DELETE CASCADE, doctor_id INT REFERENCES doctors(id) ON DELETE SET NULL, diagnosis TEXT, treatment TEXT, treated_on DATE DEFAULT CURRENT_DATE);
CREATE TABLE IF NOT EXISTS medicines(id SERIAL PRIMARY KEY, name TEXT NOT NULL, price NUMERIC(10,2) DEFAULT 0, stock INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS prescriptions(id SERIAL PRIMARY KEY, patient_id INT REFERENCES patients(id) ON DELETE CASCADE, medicine_id INT REFERENCES medicines(id) ON DELETE SET NULL, dosage TEXT, days INT);
CREATE TABLE IF NOT EXISTS bills(id SERIAL PRIMARY KEY, patient_id INT REFERENCES patients(id) ON DELETE CASCADE, amount NUMERIC(10,2), paid BOOLEAN DEFAULT FALSE, billed_on DATE DEFAULT CURRENT_DATE);
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS appt_time TEXT;
